### PR TITLE
Fix false positives in remote desync detection

### LINKED ISSUE #63: Desyncs are incorrectly reported for predicted frames
**Describe the bug**
Desyncs are reported because predicated checksums and confirmed checksums are being compared.

**To Reproduce**
See https://github.com/gschup/bevy_ggrs/issues/71

**Expected behavior**
Only the checksums of confirmed frames should be compared.

**Additional context**

Originally reported for bevy_ggrs: See https://github.com/gschup/bevy_ggrs/issues/71

### PR DESCRIPTION
**Pull request by johanhelsing**
Fixes #63 and also fixes a bug that checksums are removed prematurely if the interval is > `MAX_CHECKSUM_HISTORY_SIZE`

Confirmed working with the test case for #63 

Bonus: Remote checksums are now only checked once (removed once verified).

### CODE REVIEW

**Comment by johanhelsing** [comment]
@HeatXD may want to review, because they did the initial implementation https://github.com/gschup/ggrs/pull/50

File: src/sessions/p2p_session.rs [hunk 1]
```diff
@@ -913,14 +924,17 @@ impl<T: Config> P2PSession<T> {
                         for remote in self.player_reg.remotes.values_mut() {
```
Comment (PraxTube) [inline src/sessions/p2p_session.rs:924]: I keep getting the following panic right after peers connect in my `bevy_ggrs` project.

```
thread 'main' panicked at 'cell not found!: frame 100', ggrs-c119670c0a115c50/94604ce/src/sessions/p2p_session.rs:921:44
```

The frame not found seems to depend on the specified desync interval.

```
.with_desync_detection_mode(DesyncDetection::On { interval: 100 })
```

Changing the max prediction window and max frames behind didn't do much either

```
.with_max_prediction_window()
.with_max_frames_behind()
```

Is there anything that has to be configured in order for this PR to properly work in
exisiting `bevy_ggrs` projects, or this not expected to work with `bevy_ggrs` at all yet?

**Comment by PraxTube** [comment]
I keep getting the following panic right after peers connect in my `bevy_ggrs` project.

```
thread 'main' panicked at 'cell not found!: frame 100', ggrs-c119670c0a115c50/94604ce/src/sessions/p2p_session.rs:921:44
```

The frame not found seems to depend on the specified desync interval.

```
.with_desync_detection_mode(DesyncDetection::On { interval: 100 })
```

Changing the max prediction window and max frames behind didn't do much either

```
.with_max_prediction_window()
.with_max_frames_behind()
```

Is there anything that has to be configured in order for this PR to properly work in
exisiting `bevy_ggrs` projects, or this not expected to work with `bevy_ggrs` at all yet?

**Comment by johanhelsing** [comment]
> I keep getting the following panic right after peers connect in my `bevy_ggrs` project.
> 
> ```
> thread 'main' panicked at 'cell not found!: frame 100', ggrs-c119670c0a115c50/94604ce/src/sessions/p2p_session.rs:921:44
> ```
> 
> The frame not found seems to depend on the specified desync interval.
> 
> ```
> .with_desync_detection_mode(DesyncDetection::On { interval: 100 })
> ```
> 
> Changing the max prediction window and max frames behind didn't do much either
> 
> ```
> .with_max_prediction_window()
> .with_max_frames_behind()
> ```
> 
> Is there anything that has to be configured in order for this PR to properly work in exisiting `bevy_ggrs` projects, or this not expected to work with `bevy_ggrs` at all yet?

It's expected to work with bevy_ggrs. But very possible that I overlooked something.

I tested with box_game_p2p on this branch https://github.com/gschup/bevy_ggrs/compare/main...johanhelsing:bevy_ggrs:trigger-desync-issues?expand=1 and in my own game.

**Comment by johanhelsing** [comment]
@PraxTube are you able to reproduce your panic by modifying this branch? https://github.com/gschup/bevy_ggrs/compare/main...johanhelsing:bevy_ggrs:desync-debug?expand=1

**Comment by PraxTube** [comment]
Ah yeah, for `input_delay = 0` I don't get the panic (I had it on 2 in my tests). The desync detection seems to work properly though.

**Comment by johanhelsing** [comment]
I added a test, which is good in itself, but for some reason I don't get the panic there :/

File: src/sessions/p2p_session.rs [hunk 2]
```diff
@@ -900,10 +908,15 @@ impl<T: Config> P2PSession<T> {
...
-
-                if current % interval as i32 == 0 && frame_to_send > self.max_prediction as i32 {
+                let frame_to_send = if self.last_sent_checksum_frame == NULL_FRAME {
+                    interval as i32
+                } else {
+                    self.last_sent_checksum_frame + interval as i32
+                };
+
+                if frame_to_send <= self.sync_layer.last_confirmed_frame()
+                    && frame_to_send < self.sync_layer.last_saved_frame()
```
Comment (johanhelsing) [inline src/sessions/p2p_session.rs:918]: I'm not completely sure why `<` is needed... I'd think `<=` would be correct, but for some reason that panics. Maybe I misunderstand something about the sync layer... perhaps @gschup has some insights?

**Comment by johanhelsing** [comment]
This is ready for review now. There is one thing that bugs me (see comment above), but I'm giving up trying to understand it for now.

This is a lot more correct than the previous implementation. And has a test case that failed prior to this PR (and another one to make sure the panic reported by @PraxTube is fixed)

File: src/network/protocol.rs [hunk 3]
```diff
@@ -709,16 +708,10 @@ impl<T: Config> UdpProtocol<T> {
...
-                    frame > self.last_added_checksum_frame - MAX_CHECKSUM_HISTORY_SIZE as i32
-                });
-            }
-            self.last_added_checksum_frame = body.frame;
-            self.checksum_history.insert(body.frame, body.checksum);
-        }
+        self.pending_checksums
+            .truncate(MAX_CHECKSUM_HISTORY_SIZE - 1);
+        self.pending_checksums
+            .push_front((body.frame, body.checksum));
```
Comment (johanhelsing) [inline src/network/protocol.rs:714]: @gschup Can these reports arrive out of order?

Comment (gschup) [reply src/network/protocol.rs:714]: Anything sent over udp can potentially arrive in the wrong order. network/protocol.rs does nothing to prevent that. You can test that using clumsy and selecting the out-of-order packet option. 

I saw you changed the HashMap to a tuple queue. Are you assuming the checksums will always arrive in order?

File: src/sessions/p2p_session.rs [hunk 4]
```diff
@@ -872,20 +875,25 @@ impl<T: Config> P2PSession<T> {
...
+            DesyncDetection::On { .. } => {
+                for remote in self.player_reg.remotes.values_mut() {
+                    while remote.pending_checksums.len() > 0 {
+                        // todo: clean up when/if a drain filter variant is added for VecDeque
+                        let (remote_frame, _) = remote.pending_checksums.back().unwrap();
+                        if *remote_frame >= self.sync_layer.last_confirmed_frame() {
+                            break;
+                        }
+                        if let Some(&local_checksum) =
+                            self.local_checksum_history.get(&remote_frame)
```
Comment (johanhelsing) [inline src/sessions/p2p_session.rs:887]: If this fails, we'll loop infinitely

File: src/network/protocol.rs (hunk 3 above)
Comment (johanhelsing) [reply src/network/protocol.rs]: Converted back to a HashMap
